### ISSUE TITLE
Incompatible with new settings panel

### ISSUE THREAD

**Issue by noodlebox** [IRDeNial/BD-Even-Better-Repo#78]

**Comment by IRDeNial** [comment]
Doh!  Blah.
Guess we gotta fix that before v2 comes out.

**Comment by Hebgbs** [comment]
This affects the new BetterDiscord menus because (by sim majority_ people wanted BetterDiscord to have the different menus appear at the left side, rather than have BetterDIscord be an all-encompassing category everything is hidden in.

I advocated for this (though I didn't vote for it when Jiiks requested input). The best you can do at this point is to make a top tab bar in plugins and themes )similar to how BetterDiscord did the top tab bar previously) so _available_ themes and plugins are in their own container (don't know how you'll do that) and have it under that tab, with another for _Installable_ plugins and themes.

Alternatively you can **discontinue this project** and work with Jiiks in private to include this functionality out of the box. The website needs a little love anyway so you can spearhead a project to make a universal DB that can be used both on BetterDiscord's website and in Discord itself.

**Comment by IRDeNial** [comment]
Once V2 is officially released, and if it contains the repository explorer as expected, this plug-in will br discontinued.  Until then, we will try to fix it.

But, we're all busy and have our own lives!  Just give us time, it'll be done.

**Comment by Hebgbs** [comment]
:cool:

**Comment by mew351** [comment]
Any updates? ;)

**Comment by noodlebox** [comment]
I think this plugin is effectively discontinued. I don't have plans right now to maintain it further, and neither does @IRDeNial, afaik.

@IRDeNial if this is true, you may as well remove it from #plugin-repo for now, and just re-add it if it ends up getting fixed soon™er than BDv2's release.

**Comment by IRDeNial** [comment]
Get someone to remove it from #plugin-repo for me.  Server is almost always
offline for me.  Will update readme.

Best regards,
Michael Orozco

**Comment by IRDeNial** [comment]
Get someone to remove it from #plugin-repo for me.  Server is almost always offline for me.  Will update readme.

**Comment by noodlebox** [comment]
Done
